### ISSUE TITLE
Itens de de porta-malas, static chests sumindo aleatoriamente

### ISSUE THREAD

**Issue by P3SSOA** [beetle2k/vRP-B2K#5]
Com a base aberta, uns testers informaram de que estavam sumindo itens do porta-malas e dos baús pessoais, não faço a mínima ideia do que pode ser.

**Comment by lucastoledo95** [comment]
meu querido é problema do driver do vrp tu tem q atualizar usando o mhmatti esse driver ai é quebrado

**Comment by gusgrub** [comment]
> meu querido é problema do driver do vrp tu tem q atualizar usando o mhmatti esse driver ai é quebrado

E como resolver ?

**Comment by likizao** [comment]
ouvi falar uma correlação entre o fato do gcphone usar o mysql async..

Acho que seria interessante, converter o gcphone pro `vrp_mysql` ou converter a vRP toda pro ghmatti pegando os exemplos da vrpex, mas sei lá, acaba se tornando algo cansativo de se fazer 🤔

**Comment by Maayk** [comment]
Converter o gcphone pro vrp_mysql é burrice e converter o vrp old pro ghmatti é trabalhoso pra ter um resultado pior que o vrpex, o mais facil seria converter os scripts para o vrpex em si.

**Comment by gusgrub** [comment]
> Converter o gcphone pro vrp_mysql é burrice e converter o vrp old pro ghmatti é trabalhoso pra ter um resultado pior que o vrpex, o mais facil seria converter os scripts para o vrpex em si.

Teria um tutorial para iniciar o caminho das pedras para converter para vrpex ?
